### ISSUE TITLE
Monitoringnetten met onderzoek naar kwaliteit én kwantiteit

### ISSUE THREAD

**Issue by MarijkeHuijgen** [BROprogramma/GMN#1]
In de catalogus GMN wordt het volgende uitgangspunt gehanteerd:
In het kader van een grondwatermonitoringnet wordt onderzoek gedaan naar de kwaliteit of kwantiteit van het grondwater. Het komt ook voor dat er onderzoeken worden uitgevoerd naar beide grondwateraspecten: zowel de kwaliteit als de kwantiteit. In dat geval is wel altijd één van beide grondwateraspecten primair, en vinden er ondersteunend ook onderzoeken aan het andere aspect plaats.

Voor de aspecten kwaliteit en kwantiteit zijn er afzonderlijke monitoringdoelen. In het geval dat er in het kader van het grondwatermonitoringnet metingen aan zowel de kwaliteit als de kwantiteit worden gedaan, wordt het monitoringdoel bij het primaire, meest belangrijke aspect vastgelegd in de basisregistratie ondergrond. Naast onderzoeken aan het primaire grondwateraspect, kunnen er ook onderzoeken aan het andere aspect gekoppeld zijn aan het grondwatermonitoringnet. Bijvoorbeeld: aan een grondwatermonitoringnet waarin primair het aspect kwantiteit wordt gemonitord, kunnen naast grondwaterstandonderzoeken ook grondwatersamenstellingsonderzoeken gekoppeld worden.

VRAAG:
In welke grondwatermonitoringnetten wordt onderzoek gedaan aan zowel kwaliteit als kwantiteit? Bij team Standaardisatie BRO zijn op dit moment geen voorbeelden bekend.

**Comment by rbv305** [comment]
In de provincie Groningen wordt in de buizen van het kwantiteitsmeetnet chloride gemeten. Deze metingen worden gedaan voor de zoutcorrectie.

**Comment by PRNienhuis-WN** [comment]
In veel grondwatermonitoringnetten rondom brongebieden voor drinkwaterwinning wordt vaak zowel kwantiteit als kwaliteit gemonitord. De kwantiteitsmonitoring is vrijwel altijd het meest uitgebreid en veelal verplicht via de winvergunning, De (niet-vergunningplichtige) kwaliteitsmonitoring omvat meestal een beperkt aantal monitoringsputten en heeft een lage frequentie (intervallen van soms jaren). Die kwaliteitsmonitoring is vaak zelfs projectmatig.
Mede omdat deze metingen niet vergunningplichtig zijn zijn ze niet bekend bij DINO.

**Comment by MarijkeHuijgen** [comment]
Het voorbeeld van de chloridemetingen t.b.v. zoutcorrecties heb ik in de catalogus toegevoegd.

**Comment by MarijkeHuijgen** [comment]
Wij zien vanuit Standaardisatie op dit moment geen aanleiding om dit issue verder open te laten staan. Daarom sluit ik het.
