### ISSUE TITLE
Codelijst monitoringdoel

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#10]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
Pag 23: codelijst monitoringdoel

## Beschrijving
Er staat nu zowel ‘natuurbeheer’ als ‘natuurbescherming’ dit lijkt me een onzinnig verschil, beter om 1 van 2 te kiezen.

**Comment by tonebbing** [comment]
wordt hier niet het verschil tussen kwaliteit en kwantiteit bedoeld?  natuurbescherming gaat over kwaliteit natuurbeheer over kwantiteit

**Comment by MarijkeHuijgen** [comment]
Het verschil is bewust gemaakt. En het gaat inderdaad om het onderscheid tussen kwaliteit en kwantiteit.

Zie bijlage 'Wettelijk kader en monitoringdoel': 
natuurbescherming -> grondwaterkwaliteit i.h.k.v. wet natuurbescherming
natuurbeheer -> grondwaterstanden i.h.k.v. wet natuurbescherming.
