### ISSUE TITLE
wijziging netwerk of einddatum netwerk?

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#11]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
Pag 24: codelijst registratiestatus

## Beschrijving
Vraag is als je een monitoringnetwerk wijzigt er dan sprake is van een nieuw netwerk of dat je inderdaad een nieuwe versie in de tijd krijgt. De ervaring leert dat er in de tijd vaak wel wisseling/uitval van locaties is.

**Comment by MarijkeHuijgen** [comment]
Zie paragraaf 5 'Object met een levensloop' in de catalogus:
Grondwatermonitoringnet is een object met levenscyclus. Er zijn wijzigingen gedurende de levenscyclus van het object, o.a. veranderingen in de verzameling meetpunten. Dergelijke veranderingen horen bij het object, en leiden niet tot een nieuw object.
