### ISSUE TITLE
Relevantie IMBRO/A bij GMN

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#13]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Kwaliteitsregime IMBRO – IMBRO/A

## Beschrijving
Het is me onduidelijk waarom bij een grondwatermonitoringnet tussen twee verschillende kwaliteitsregimes kan worden gekozen; IMBRO (kader inwinning bekend) of IMBRO/A (kader inwinning onbekend). Van een monitoringnet is per definitie bekend wat het kader van de inwinning is; je verzamelt gegevens namelijk gegroepeerd met een reden. 

Wanneer je een monitoringnet onder IMBRO/A definieert, dan zeg je feitelijk dat je wel een naam aan het monitoringnet meegeeft maar geen idee hebt waarom dit een samenhangende groep is. Tevens kun je er alleen IMBRO/A (=historische) gegevens aan koppelen. Gegevens uit nieuwe meetronden (=IMBRO) zijn niet toegestaan. Wanneer je een monitoringnet onder IMBRO definieert, dan heb je als bronhouder wel de vrijheid om daar zowel IMBRO/A als IMBRO gegevens aan te koppelen. 

## Oplossingsrichting
Vanuit bronhouders- en gebruikersperspectief is het niet zinnig om IMBRO/A grondwatermonitoringnetten te definiëren. Mijn voorstel is dan ook om ieder grondwatermonitoringnet standaard onder IMBRO te plaatsen.

**Comment by AnnitaVijverberg** [comment]
**Harry van Manen, Rijkswaterstaat:**
## Waar
Toelichting 8 Samenhang en consistentie ………… blz 31

## Beschrijving
Bij de laatse bullit wordt de samenhang van de kwaliteitsregimes besproken. Omdat IMBRO/A ook gekoppeld kan worden aan een IMBRO/A monitoringnet wordt een aanduiding hiervoor gemist.

## Oplossingsrichting
Het gecombineerde kwaliteitsregime IMBRO-IMBRO/A toevoegen als mogelijke invulling van het attribuut kwaliteitsregime van grondwatermonitoringnetten.

**Comment by lvdbrink** [comment]
**Mariëlle van Vliet, TNO:** 

> Grondwatermonitoringnetten   onder kwaliteitsregime IMBRO/A zijn bedoeld als administratieve oplossing om   in de basisregistratie ondergrond historische onderzoeksgegevens te kunnen   registreren waarvan niet (meer) bekend is binnen welk(e) monitoringnet(ten)   deze tot stand zijn gekomen.

(Historische) onderzoeksgegevens (GAR en GLD) kunnen   toch ook opgenomen worden zonder dat ze gekoppeld zijn aan een   grondwatermeetnet?          Het toch niet zo dat een grondwateranalyse of grondwaterstand alleen   ingevoerd kan worden als deze ook aan een grondwatermeetnet is gekoppeld?

GAR of   GLD ook los van GMN opnemen in bro.

**Comment by AnnitaVijverberg** [comment]
De koppeling aan een GMN is verplicht, ook bij historische onderzoeksgegevens met een IMBRO/A kwaliteitsregime. Voor historische onderzoeksgegevens is het wettelijk kader en het monitoringdoel niet altijd bekend. Deze historische gegevens kunnen aan een grondwatermontoringnet gehangen worden met een IMBRO/A kwaliteitsregime.

Zie ook paragraaf 7 'Kwaliteitsregime IMBRO/A' :
IMBRO/A biedt een voorziening voor bronhouders om een overkoepelend grondwatermonitoringnet te registreren om hun historische GAR's en GLD's aan een  te koppelen als niet meer te achterhalen is voor welk grondwatermonitoringnet/monitoringdoel ze precies gemeten zijn. Onder IMBRO/A is het mogelijk om monitoringdoel 'onbekend' te kiezen en om 'onbekend' te kiezen als begin- en/of einddatum van het grondwatermonitoringnet.

Een registratieobject kan maar 1 kwaliteitsregime hebben. Het valt in zijn geheel onder IMBRO of onder IMBRO/A. Het kwaliteitsregime heeft alleen betrekking op het betreffende registratieobject, en niet op andere objecten die eventueel eraan gekoppeld zijn. De gekoppelde registratieobjecten hebben hun eigen kwaliteitsregime.
