### ISSUE TITLE
Kadastrale eenheden

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#16]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Kadastrale eenheden

## Beschrijving
Grondwatermonitoringnetten behoren altijd toe aan een (of meerdere) kadastrale eenheden; een provinciegrens, gemeentegrens, grondwaterlichaam enz. Worden koppelingen aan dit soort kadastrale grenzen automatisch gemaakt? Het is namelijk van groot (gebruikers)belang voor een juiste selectie van gegevens. 

## Oplossingsrichting
Ik wil aanraden om dat automatisch te doen, waarbij de bronhouder van het grondwatermonitoringnet altijd de mogelijkheid behoudt om daar wijzigingen in aan te brengen. Er kunnen namelijk legitieme redenen voor afwijkingen bestaan.

**Comment by MarijkeHuijgen** [comment]
Koppeling van grondwatermonitoringnet aan kadastrale eenheden is niet in scope. 
- Tijdens het proces van scopebepaling is het vastleggen van ruimtelijke begrenzing van een monitoringgebied besproken. Er was toen geen draagvlak om dit in de BRO vast te leggen.
- Directe koppelingen met gegevens in andere basisregistraties zijn voor de BRO op dit moment buiten scope.
- Koppelen van gegevens op deze manier brengt veel vragen met zich mee. Het kost tijd om dit goed uit te zoeken en af te stemmen. Daardoor is het in deze fase niet meer mogelijk om dit mee te nemen.

Als na realisatie in de praktijk blijkt dat er een grote behoefte aan dit soort koppelingen is, dan kan dit in de beheerfase als wens worden ingebracht.
