### ISSUE TITLE
Monitoringsdoel bij primaire aspect

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#17]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Pag 9. 1.1.2.3. 

## Beschrijving
Toelichting: Het monitoringsdoel wordt bij het primaire, meest belangrijke aspect vastgelegd.
Wie bepaalt dit? Je kan toch beter aparte meetnetten definiëren dan voorkom je deze keuze/onduidelijkheid. Wat wordt hier bedoelt met ‘aspect’? 

## Oplossingsrichting
Graag duidelijkheid over verschaffen.

**Comment by MarijkeHuijgen** [comment]
De bronhouder bepaalt dit. 
Zie paragraaf 6 'Kwaliteit en kwantiteit':
Voorbeeld uit de catalogus: in sommige monitoringnetten voor kwantiteit worden ook chloridegehaltes gemeten ten behoeve van eventuele correcties (‘zoutcorrecties’).
In dit geval is het primaire aspect van het grondwatermonitoringnet kwantiteit, en heeft het grondwatermonitoringnet een monitoringdoel dat hoort bij kwantiteit (en niet bij kwaliteit). Ondersteunend aan dat kwantiteit-monitoringdoel vinden voor het grondwatermonitoringnet ook grondwatersamenstellingsonderzoeken plaats (kwaliteit). De bronhouder hoeft hier niet per se een apart grondwatermonitoringnet voor te definiëren. Dat zou in dit geval niet wenselijk zijn, omdat de kwaliteitsmetingen ook het kwantiteit-monitoringdoel dienen.
Zie bijlage 'Wettelijk kader en monitoringdoel': hierin staat per monitoringdoel aangegeven bij welk aspect het hoort.
