### ISSUE TITLE
Einddatum meetpunt

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#19]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Pag 18: 1.1.3.2

## Beschrijving
Regels. De einddatum van het meetpunt ligt niet na de einddatum van het grondwatermonitoringnet
Een meetpunt kan na beëindiging van een bestaand meetnet toch ook worden opgenomen in een nieuw (te ontwikkelen)  meetnet. Waarom een einddatum bij een meetpunt toevoegen?

## Oplossingsrichting
Onjuiste bewering. Graag aanpassen in de catalogus.

**Comment by MarijkeHuijgen** [comment]
De einddatum van een meetpunt geeft aan dat na die datum het betreffende meetpunt geen onderdeel meer uitmaakt van het grondwatermonitoringnet. De buis in de grondwatermonitoringput die het meetpunt vormde blijft bestaan, en kan daarna nog gewoon onderdeel zijn of worden van andere monitoringnetten. 
Wanneer een monitoringnet eindigt, dan zijn er ook geen meetpunten meer onderdeel van het net. De meetpunten van het monitoringnet eindigen dan dus ook. 
Zie ook uitleg bij issue 45.
