### ISSUE TITLE
Huidige monitoringnetten zonder wettelijk kader?

### ISSUE THREAD

**Issue by MarijkeHuijgen** [BROprogramma/GMN#2]
In de workshop over aanleveren van gegevens in het grondwaterdomein op 25 januari is de wens geuit om aan de lijst van wettelijk kaders voor GMN (codelijst KaderAanlevering) de waarde 'geen' toe te voegen, voor monitoringnetten zonder wettelijk kader. 
Uitgangspunt voor het registratieobject GMN in de BRO is dat alle grondwatermonitoring door of in opdracht van bestuursorganen plaatsvindt vanuit een doel dat volgt uit een wettelijke taak van het bestuursorgaan. En dus dat alle grondwatermonitoring die op dit moment plaatsvindt, een wettelijk kader heeft. Als dit niet juist is, dan ontvangt het team Standaardisatie BRO graag informatie over voorbeelden waarvoor dit niet geldt.

N.B.
Onder IMBRO/A is de waarde 'onbekend' mogelijk voor kader aanlevering. Dit is voor monitoringnetten die ervoor dienen om historische gegevens (GAR en GLD) aan te koppelen, bijvoorbeeld bij het converteren van bestaande gegevens uit DINO.
Onder IMBRO (voor huidige grondwatermonitoringnetten) is deze waarde niet toegestaan.

VRAGEN:
* Wat is de achtergrond voor de wens om kader aanlevering 'geen' vast te leggen in de BRO?
* Welke (huidige) grondwatermonitoringnetten die in scope zijn voor de BRO hebben geen wettelijk kader?
* Wat zijn in dat geval het kader en het doel van de monitoring in dat net?

**Comment by rbv305** [comment]
Een voorbeeld van een meting zonder wettelijk kader is dat we tijdelijk de grondwaterstand meten bij een huis van een burger die last heeft van grondwateroverlast. We doen dit vanuit onze verantwoordelijkheid als grondwaterbeheerder en in die zin is er weer wel een wettelijk kader. Maar dit valt waarschijnlijk niet onder het wettelijk kader zoals in de BRO vastgelegd.

**Comment by MarijkeHuijgen** [comment]
Dank voor de input!
Tijdelijk n.a.v. een heel lokaal probleem of klacht een paar metingen doen, valt inderdaad niet binnen de scope van (langdurig, minstens een jaar) monitoren in een monitoringnet.

**Comment by MarijkeHuijgen** [comment]
Wij zien vanuit Standaardisatie op dit moment geen aanleiding om dit issue verder open te laten staan. Daarom sluit ik het.
Mocht er in de toekomst aanleiding zijn, dan kunnen we het issue heropenen.
