### ISSUE TITLE
Ruimtelijke schaal monitoring

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#20]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Pag 25 1 Grondwatermonitoring, 4e alinea, laatste regel

## Beschrijving
’Aan de ruimtelijke schaal van monitoring zijn voor de basisregistratie ondergrond geen grenzen gesteld.’
De Nederlandse grens is toch wel een eis, meetpunten uit o.a. België en Duitsland kunnen toch niet worden opgenomen in een meetnet/geregistreerd in de BRO?

## Oplossingsrichting
Graag aanpassen in de catalogus.

**Comment by MarijkeHuijgen** [comment]
Inderdaad geldt voor de gehele basisregistratie ondergrond dat deze (alleen) gegevens bevat over de ondergrond van Nederland en zijn Exclusieve Economische Zone (EEZ). De EEZ is het gebied op de Noordzee waar Nederland economische rechten heeft.
In de catalogus vermelding hiervan toegevoegd.
