### ISSUE TITLE
samenhang registratieobjecten

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#22]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Relatie met andere registratieobjecten

## Beschrijving
Als we in GMN vastleggen in welke meetpunten (in een bepaalde periode) tot een bepaald meetnet behoren, vraag ik me af we in GAR (1.1.3) ook (verplicht) moeten vastleggen tot welk net(ten) een meting of monster behoort. In ieder geval moet er dan wel een goede tool beschikbaar komen die de consistentie controleert en waarmee we de toewijzing kunnen regelen. Zeker ook bij grondwaterstanden wordt dat een meervoudige boekhouding.

## Oplossingsrichting
Graag duidelijkheid over verschaffen.

**Comment by MarijkeHuijgen** [comment]
Bij GAR is het inderdaad verplicht om vast te leggen bij welk(e) grondwatermonitoringnet(ten) het onderzoek hoort.
Wat betreft tooling: dit is een functionele vraag, die we niet in de catalogus adresseren. De catalogus gaat over de formele samenhang van de gegevens.
