### ISSUE TITLE
Vastleggen subnetten of aanvullende gegevens

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#23]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Vast te leggen informatie

## Beschrijving
Bij ons huidige GMN (in GIS) leg ik nu ook vast welke van de 3 overige percelen er per (3-jaarlijkse) kwaliteitsmeetronde gemeten moeten worden. Ik zou het jammer vinden als ik die onderverdeling niet in de BRO opgeven. De vraag ‘waar meten we bestrijdingsmiddelen?’ zou primair op basis van GMN beantwoord moeten kunnen worden.
M.i. moeten we ook afstemmen hoe we dat zo uniform mogelijk doen. Bijvoorbeeld één algemeen KRW kwaliteitsmeetnet definiëren (met begin en einddatum, conform de opgave bij de EU) en daarnaast ook submeetnetten per perceel en  evt per meetronde (begin en einddatum/ jaartal). Volgens mij biedt GMN hier ruimte voor.
‘1.1.2.4 / 2.2.1 Grondwateraspect’ slaat nu op het onderscheid tussen kwantiteit en kwaliteit. Daar zouden m.i. dus ook subaspecten aan toegevoegd moeten worden zoals ‘bestrijdingsmiddelen’, ‘industriële stoffen’, ‘enkel Cl of EC’ of zoiets als een ‘zoet-zout grensvlak’ (zoutwachter / Slimflex).

## Oplossingsrichting
Graag   duidelijkheid over verschaffen.

**Comment by MarijkeHuijgen** [comment]
Hoe de grondwatermonitoringnetten zijn ingericht (welke meetpunten zitten erin e.d.) is aan de bronhouder. Het is mogelijk om een monitoringnet te definiëren dat bestaat uit een deel van de meetpunten van een ander monitoringnet. Zie ook #15. Het afstemmen van de indeling van monitoringnetten kunnen bronhouders indien gewenst onderling doen.

Wat betreft subaspecten:
Dit is niet in scope geweest bij het standaardiseren. Er is een brede discussie nodig om uit te zoeken of dit geschikt is om te standaardiseren. 
Als deze wens blijft bestaan, dan kan deze later nog een keer worden ingediend. In de beheerfase van de standaard kan dan gekeken worden of de standaard hiermee uitgebreid moet/kan worden.
