### ISSUE TITLE
Beëindiging/vervanging meetpunt

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#24]
provincies via Platform Meetnetbeheerders:
## Type issue
Publieke consultatie

## Waar
Beëindiging/vervanging meetpunt

## Beschrijving
Kan bij GMN of bij voortijdige beëindiging van een put de relatie met een vervangend meetpunt vastgelegd worden? Graag duidelijkheid verschaffen.

**Comment by AnnitaVijverberg** [comment]
We zijn voornemens de catalogus hierop aan te passen zodat dit mogelijk wordt.

**Comment by MarijkeHuijgen** [comment]
In de workshop gehouden op 18 juli 2019 is besloten om het concept meetpunt in het grondwatermonitoringnet aan te passen, zodat een meetpunt gevormd kan worden door een opeenvolging van verschillende putfilters.
Het domeinmodel en de catalogus zijn hierop aangepast.
