### ISSUE TITLE
object-ID bronhouder

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#25]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
1.1.1.3 blz 5

## Beschrijving
Dit attribuut is niet verplicht en hoeft geen gegeven te bevatten.

## Oplossingsrichting
Mogelijk geen waarde : JA; Indicatie kardinaliteit: 0,1

**Comment by MarijkeHuijgen** [comment]
Het gegeven 'object-ID bronhouder' wordt alleen uitgeleverd aan de dataleverancier en de bronhouder. Het is in de registratie opgenomen om de communicatie tussen de registerbeheerder en de bronhouder of dataleverancier te vergemakkelijken.
Het gegeven is verplicht omdat het gebruikt kan worden als identificerend gegeven voordat er door de BRO een BRO-ID aan is toegekend. Bijvoorbeeld als er iets misgaat in het proces rond registreren van een object.

Toelichting hierover opgenomen bij het attribuut.
