### ISSUE TITLE
Kaderaanlevering GMN vs GMW

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#26]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
1.1.2.3 blz 9

## Beschrijving
De kaderaanlevering van het grondwatermonitoringnet kan afwijken van de kaderaanlevering van de grondwatermonitoringput.

## Oplossingsrichting
Bij de toelichting toevoegen: De rechtsgrond van een grondwatermonitoringsput kan afwijken van de rechtsgrond van het gekoppelde Grondwatermonitoringnet.

**Comment by MarijkeHuijgen** [comment]
Dit zijn inderdaad verschillende soorten gegevens. Het kader aanlevering van een grondwatermonitoringnet kan anders zijn dan het kader aanlevering van een grondwatermonitoringput waarnaar vanuit een meetpunt in het grondwatermonitoringnet wordt verwezen.
Hierover uitleg toegevoegd in de toelichting bij het attribuut 'kader aanlevering'.
