### ISSUE TITLE
Definieren formaat "Registratieobjectcode"

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#27]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
1.1.3.4.2 blz 18

## Beschrijving
Het formaat "Registratieobjectcode" wordt niet beschreven of toegelicht in dit document en in het Inleiding document.

## Oplossingsrichting
Borgen dat alle formatten worden gedefinieerd in dit document of een duidelijk verwijzing naar het Inleiding document (indien de beschrijving van het formaat daar is opgenomen).

**Comment by lvdbrink** [comment]
Er zijn een aantal standaard formaten, zoals Registratieobjectcode, maar ook bijv. Tekst, Meetwaarde en Nummer, die in vrijwel alle registratieobjecten worden gebruikt. Om te voorkomen dat de toelichting van deze standaard formaten steeds opnieuw in elke ministeriële regeling moet worden opgenomen, is het opgenomen in de inleiding. De inleiding is geldig voor meerdere registratieobjecten.

We begrijpen dat het voor gebruikers lastig is dat het gesplitst is, daarom maken we ook een gebruiksvriendelijke HTML versie waarin de volgorde wat logischer is.
