### ISSUE TITLE
Definieren formaat "Nummer3"

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#28]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
1.1.3.4.2

## Beschrijving
Het formaat "Nummer3" is niet gedefinieerd. Graag definieren.

**Comment by lvdbrink** [comment]
Er zijn een aantal standaard formaten, zoals Registratieobjectcode, Meetwaarde, Tekst en Nummer, die in vrijwel alle registratieobjecten worden gebruikt (vaak met een aanduiding van de veldlengte erachter). Om te voorkomen dat de toelichting van deze standaard formaten steeds opnieuw in elke ministeriële regeling moet worden opgenomen, is het opgenomen in de inleiding. De inleiding is geldig voor meerdere registratieobjecten.

We begrijpen dat het voor gebruikers lastig is dat het gesplitst is, daarom maken we ook een gebruiksvriendelijke HTML versie waarin de volgorde wat logischer is.
