### ISSUE TITLE
Codelijst grondwateraspect

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#29]
Harry van Manen, Rijkswaterstaat:
## Waar
Toelichting 6 Kwaliteit en kwantiteit blz 30 

## Beschrijving
Voor het grondwateraspect kan helaas alleen het primaire aspect worden vastgelegd. Daardoor wordt soms niet alle gewenste informatie zicht bij een gerichte zoekactie. Bijvoorbeeld het zoeken naar alle monitoringnetten in een regio waarbij grondwaterstanden worden vastgelegd. 

## Oplossingsrichting
De codelijst 2.2.1 "Codelijst details Grondwateraspect" uitbreiden met beide aspecten, eventueel met daarbij het primaire aspect. Dus uitbreiding: - kwaliteit + kwantiteit (primair kwaliteit) - kwantiteit + kwaliteit (kwantiteit primair)

**Comment by lvdbrink** [comment]
**Mariëlle van Vliet, TNO:** 
Over 2.2.1   Codelijst details grondwateraspect, Definitie: 

De   omschrijving van deze definitie lijkt me niet juist.  Foutieve 'copy-paste' actie.

Aanpassen   naar juiste definitie

**Comment by AnnitaVijverberg** [comment]
De definitie is aangepast.

**Comment by MarijkeHuijgen** [comment]
In reactie op het punt van Harry van Manen:

Het vastleggen van het grondwateraspect van het grondwatermonitoringnet is bedoeld om het voor de gebruiker makkelijker te maken snel onderscheid te maken tussen monitoringnetten met een monitoringdoel voor kwaliteit vs   kwantiteit. Het is niet bedoeld om weer te geven welke soort onderzoeken er daadwerkelijk aan het monitoringnet gekoppeld worden/zijn. Daar zit geen   koppeling tussen. 
Het is niet eenvoudig om een uitbreiding zoals hier voorgesteld te   standaardiseren. Er moet dan onder andere duidelijk (gestandaardiseerd) zijn   wat de criteria zijn voor een secundair aspect, hoe zich dat verhoudt tot de   onderzoeken die daadwerkelijk gekoppeld zijn aan het grondwatermonitoringnet,   en hoe dat in de tijd kan veranderen. Deze discussies kunnen we nu niet   voeren.     
Als het in de toekomst relevant of gewenst blijkt/blijft om deze uitbreiding te onderzoeken, dan kan dit als wens ingebracht worden in de beheerfase van de standaard.     

Overigens is op dit moment nog niet uitgekristalliseerd hoe de   zoekfunctionaliteit en de uitgifte van gegevens over verschillende   registratieobjecten in het grondwaterdomein vorm gaan krijgen.
