### ISSUE TITLE
Monitoringsbuizen van andere bronhouders opnemen in monitoringsnet

### ISSUE THREAD

**Issue by PeterDorsman** [BROprogramma/GMN#3]
## Type issue
Publieke consultatie

## Waar
Paragraaf 4 pagina 28. 

## Samenvatting
Uit de tekst wordt niet duidelijk of je ook buizen van andere bronhouders aan je meetnet als meetpunt mag koppelen.

## Beschrijving
In het kader van samenwerking is het niet denkbeeldig dat je ook graag monitoringsbuizen van andere bronhouders (in onderling overleg bv waterschap en gemeente) op wil nemen in je eigen meetnet. Uit de tekst wordt niet duidelijke of dit wel/niet mogelijk is.

## Oplossingsrichting
Vanuit toekomstig perspectief lijkt me dit een optie die open gehouden moet worden.

**Comment by MarijkeHuijgen** [comment]
Het is zeker mogelijk om buizen van andere bronhouders als meetpunt te koppelen aan een grondwatermonitoringnet.

In de catalogus hierover verduidelijking opgenomen.
