### ISSUE TITLE
Codelijst KaderAanlevering

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#30]
Harry van Manen, Rijkswaterstaat:
## Type issue
Publieke consultatie

## Waar
Bijlage: Wettelijk kader en monitoringdoel. Blz 33

## Beschrijving
De codelijst van Kaderaanlevering is niet geheel in overeenstemming met de codelijst van Kaderaanlevering van Grondwaterminitoringput. 

## Oplossingsrichting
De codelijst van Kaderaanlevering is niet geheel in overeenstemming met de codelijst van Kaderaanlevering van Grondwaterminitoringput.

**Comment by MarijkeHuijgen** [comment]
Kader aanlevering van GMW en van GMN zijn verschillende gegevens. 
Kader aanlevering van het grondwatermonitoringnet geeft de wettelijke basis/verplichting voor het monitoren. We hebben bewust gekozen voor de huidige codelijst, op basis van de huidige wetgeving.
Aan het standaardiseren van kader aanlevering van de grondwatermonitoringput is een ander traject met andere overwegingen vooraf gegaan. Het valt niet binnen de kaders van het standaardiseren van het registratieobject Grondwatermonitoringnet om de codelijst van kader aanlevering van het registratieobject Grondwatermonitoringput het heroverwegen of herzien.
