### ISSUE TITLE
Koppeling aan minimaal 1 put

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#31]
G. Menting, RWS:
## Type issue
Publieke consultatie

## Waar
blz 17 (relaties)

## Beschrijving
De minimale versie maakt het mogelijk, dat het monitoringnetwerk aan geen enkele locatie gekoppeld is. dat lijkt mij niet wenselijk.

## Oplossingsrichting
Kardinaliteit 0..* aanpasen naar 1..*

**Comment by AnnitaVijverberg** [comment]
Ook vanuit het ministerie, juridica, is aangegevens dat een registratieobject altijd een verwijzing naar een locatie moet hebben. Aan een monitoringnet moet daarom altijd minimaal 1 put zijn gekoppeld.

**Comment by MarijkeHuijgen** [comment]
Aangepast. Er moet minstens 1 meetpunt zijn in een grondwatermonitoringnet.
