### ISSUE TITLE
Naam van het registratieobject onjuist

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#33]
Mariëlle van Vliet, TNO

## Type issue
Publieke consultatie

## Waar
Gehele document

## Beschrijving
`Grondwatermonitoringnet:`   Dit is geen juist Nederlands woord.

## Oplossingsrichting
Gebruik   hiervoor grondwatermeetnet of grondwatermonitoringsnetwerk.

**Comment by AnnitaVijverberg** [comment]
De term Grondwatermonitoringnet is vanuit de historie gegroeid en is inmiddels vastgelegd in wetgeving. We gaan het in deze fase niet aanpassen.
