### ISSUE TITLE
Onduidelijkheid in definitie Registratieobject

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#34]
Mariëlle van Vliet, TNO

## Type issue
Publieke consultatie

## Waar
Paragraaf 1.1.1

## Beschrijving
Leesbaarheid van de definitie van Registratieobject verbeteren.

> Het geheel van gegevens dat betrekking heeft op een grondwatermonitoringnet: een verzameling locaties waar periodiek onderzoek aan het grondwater op een of meerdere _bepaalde_ dieptes wordt gedaan om de toestand van het grondwater in het gebied vanuit een perspectief te bepalen, om de eventuele veranderingen daarin te kunnen volgen.

## Oplossingsrichting
haal het   woord 'bepaalde' weg om de leesbaarheid te vergroten.

**Comment by AnnitaVijverberg** [comment]
Het woord 'bepaalde' geeft aan dat het om specifieke dieptes gaat. Dit woord is bewust gebruikt en met dit woord erbij is het zorgvuldiger. Deze definitie staat ook in het scopedocument. Hoewel het zonder dit woord wellicht beter leesbaar is hebben we besloten het erin te laten staan.
