### ISSUE TITLE
Tijdstip voltooiing registratie

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#35]
Mariëlle van Vliet, TNO

## Type issue
Publieke consultatie

## Waar
Paragraaf 1.1.2.5.4 

## Samenvatting
Een meetnet moet in de loop van de tijd kunnen worden aangepast.

## Beschrijving
Na   tijdstip voltooiing registratie kunnen geen gegevens meer worden aangeboden:   betekent dit dat er ook geen verwijzingen meer naar buis en filter kan worden   gemaakt? Dan ben ik het hier niet mee eens.

Een   meetnet bestaat uit een verzameling buizen. Deze gaan helaas kapot en worden   vervangen. Een meetnet is dus niet een statisch gegeven, maar moet kunnen   worden aangepast. Dat is wat anders dan corrigeren.           Daarnaast zijn er ingrijpendere wijzigingen bijvoorbeeld na een   optimalisatie van een meetnet.      Een geoptimaliseerd meetnet wordt welllicht wel als een nieuw meetnet   opgenomen, maar dat lijkt me afhankelijk van de mate waarin veranderingen   worden doorgevoerd.

Zie ook #11 

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by AnnitaVijverberg** [comment]
Het gegeven 'tijdstip voltooiing registratie' wordt pas gevuld op het moment dat de levenscyclus van het grondwatermonitoringnet eindigt (in de werkelijkheid). Dat betekent dat pas wanneer de bronhouder een einddatum doorgeeft voor het grondwatermonitoringnet, dat op dat moment dit 'tijdstip voltooiing registratie' wordt gevuld, dit gebeurd automatisch. Gedurende de levenscyclus van het grondwatermonitoringnet kunnen wijzigingen in meetpunten e.d. worden doorgevoerd.
