### ISSUE TITLE
Begindatum Grondwatermonitoringnet onder IMBRO/A

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#36]
Mariëlle van Vliet, TNO

## Type issue
Publieke consultatie

## Waar
Paragraaf 1.1.2.6 en 1.1.2.7

## Samenvatting
Regel IMBRO/A te ruim.

## Beschrijving
Domein   IMBRO/A: OnvolledigeDatum.      Waarom is dit een 'onvolledige datum?' Ook voor   imbro/a heb je toch altijd een volledige datum, namelijk de eerste of laatste   datum waarop grondwatermeting is uitgevoerd?

## Oplossingsrichting
Type wijzigen naar volledig datum.

**Comment by MarijkeHuijgen** [comment]
Zie ook #47.
In het registratieobject Grondwatermonitoringnet is IMBRO/A een voorziening voor bronhouders om een overkoepelend grondwatermonitoringnet te registreren om hun historische GAR's en GLD's aan te koppelen als niet meer te achterhalen is voor welk grondwatermonitoringnet/monitoringdoel ze precies gemeten zijn. Er wordt daarom d.m.v. OnvolledigeDatum de mogelijkheid geboden om een minder precies afgebakende periode van monitoren op te geven, zodat schijnprecisie wordt vermeden. 
De periode van monitoren (begindatum en einddatum van het grondwatermonitoringnet) is bedoeld om aan te geven over welke periode er gemonitord wordt voor het specifieke doel van het monitoringnet. De datums waarop onderzoeken worden uitgevoerd vallen binnen deze periode, maar de periode van monitoren kan ook eerder beginnen dan het eerste onderzoek is uitgevoerd, of later eindigen dan het laatste onderzoek is uitgevoerd.
