### ISSUE TITLE
Onduidelijkheid in codelijst KaderAanlevering

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#37]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Paragraaf 2.2.2

## Samenvatting
Onduidelijkheid in de definitie van codelijst KaderAanlevering

## Beschrijving
> De rechtsgrond op basis waarvan, of bij afwezigheid   daarvan, de activiteit naar aanleiding waarvan, het betreffende gegeven is   aangeleverd aan de basisregistratie ondergrond.
--

Volgens mij ontbreekt één keer   het woordje 'of' en een komma. Daardoor slecht leesbaar / niet duidelijk. 

## Oplossingsrichting
De rechtsgrond op basis waarvan, of bij afwezigheid daarvan, **of** de activiteit naar aanleiding   waarvan, het   betreffende gegeven is aangeleverd aan de basisregistratie ondergrond.

**Comment by AnnitaVijverberg** [comment]
Toevoegen van het woordje 'of' is onjuist. De voorgestelde komma staat er. Omdat dit een generieke definitie is die elders in de BRO ook voorkomt hebben we ervoor gekozen het niet te wijzigen.
