### ISSUE TITLE
Onduidelijke naam 'monitoringdoel'

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#38]
Mariëlle van Vliet, TNO: 

## Type issue
Publieke consultatie

## Waar
in het gehele document en specifiek 2.2.3 Codelijst details Monitoringdoel

## Samenvatting
Monitoringdoel   is ongebruikelijk woord.

## Oplossingsrichting
Gewoonlijk   wordt het woord 'monitoring**s**doel'   gebruikt!

**Comment by AnnitaVijverberg** [comment]
Het genootschap Onze taal geeft aan dat het wel of niet schrijven van een tussen -s een vrije kwestie is. Dat meestal op gehoor de juiste keuze gemaakt kan worden. Wij hebben destijds gekozen voor ‘monitoringput’ en daarna voor ‘monitoringnet’, allebei zonder tussen -s. Daarna hebben we die lijn doorgetrokken naar ‘monitoringdoel’.
