### ISSUE TITLE
Foutief gebruik term 'uitgestrektheid' in toelichting

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#39]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting   1. Grondwatermonitoring, 3e alineau

## Samenvatting
Foutief gebruik term 'uitgestrektheid' in toelichting.

## Beschrijving
Uitgestrektheid   betekent 'grote omvang' of 'grote oppervlakte'. Het gaat hier niet om een   'grote' oppervlakte, maar om de grootte van een oppervlakte.

## Oplossingsrichting
vervangen   door schaal of grootte

**Comment by AnnitaVijverberg** [comment]
Suggestie overgenomen.
