### ISSUE TITLE
Periode bemonstering van meetnet

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#40]
Mariëlle van Vliet, TNO: 

## Type issue
Publieke consultatie

## Waar
Toelichting   1. Grondwatermonitoring, 4e alineau

## Samenvatting
Periode bemonstering van meetnet.

## Beschrijving

> De periode van een jaar is lang genoeg voor het   uitfilteren van de effecten van kleinschalige en kortdurende invloeden, zodat   de informatie die in de basisregistratie wordt vastgelegd blijvende   gebruikswaarde heeft.

Dit lijkt me niet de juiste reden om alleen meetnetten die langer dan 1   jaar lopen, in de bro op te nemen.           Ook in een meetnet, dat korter dan één jaar wordt bemonsterd, worden   waardevolle metingen verricht.

## Oplossingsrichting
Deze   zin weglaten lijkt me beter.

**Comment by AnnitaVijverberg** [comment]
Bij monitoren vanaf 1 jaar geldt een verplichting om aan te leveren aan de BRO, dit staat in de wet. Voor monitoring korter dan een jaar geldt dat er geen verplichting is maar dat de bronhouder zelf mag beslissen of hij de gegevens wel of niet aanlevert aan de BRO. Dit staat in het Staatsblad van het Koninkrijk der Nederlanden 421, Besluit basisregistratie ondergrond, 25 oktober 2017, artikel 2.3.1 over de grondwatermonitoringput.
