### ISSUE TITLE
Bodemkwaliteitsmeetnetten binnen scope

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#41]
**Mariëlle van Vliet, TNO:** 

## Type issue
Publieke consultatie

## Waar
Toelichting   1. Grondwatermonitoring, 5e alineau

## Samenvatting
Bodemkwaliteitsmeetnetten vallen binnen de scope.

## Beschrijving

> In de Regels omtrent de basisregistratie ondergrond en   het Besluit basisregistratie ondergrond staat dat de basisregistratie   ondergrond vooralsnog geen milieukwaliteitinformatie bevat. Voor het   grondwatermonitoringdomein zijn monitoringnetten rondom milieuhygiënische   projecten, waarin het met name gaat om het    monitoren van de verontreiniging van de bodem en het grondwater,   daarmee voorlopig buiten scope geplaatst.

Dit betekent dat bodemkwaliteitsmeetnetten ook binnen de scope vallen.

## Oplossingsrichting
Gehele   document aanpassen aan toevoegen van bodemkwaliteitsmeetnetten.

**Comment by MarijkeHuijgen** [comment]
Bodemkwaliteitsmeetnetten vallen niet binnen de scope. In het scopedocument GMN staat "De monitoring van de kwaliteit van de ondiepe bodem met het daarin aanwezige grondwater (bodemvocht), zoals dat gedaan wordt om de gevolgen van met name landbouwactiviteiten te kunnen volgen, valt binnen de scope van de BRO, maar buiten de scope van het registratieobject grondwatersamenstellingsonderzoek. Die vorm van monitoring valt binnen het BROdomein bodemkwaliteit (in landelijk gebied)." 
Om de scope zoals beschreven in het scopedocument explicieter te benoemen is in de catalogus in paragraaf 'Grondwatermonitoring' als laatste alinea toegevoegd: "De monitoring van de kwaliteit van de ondiepe bodem met het daarin aanwezige grondwater (bodemvocht), zoals dat gedaan wordt om de gevolgen van met name landbouwactiviteiten te kunnen volgen, valt buiten de scope van het registratieobject Grondwatermonitoringnet. De volledige scopeafbakening is beschreven in het Scopedocument grondwatermonitoringnet GMN."
