### ISSUE TITLE
Formulering in Toelichting Domein grondwatermonitoring in de BRO

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#42]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting   2. Domein grondwatermonitoring in de bro, 3e pagina, 2e alinea

## Samenvatting
Formulering in Toelichting Domein grondwatermonitoring in de BRO.

## Oplossingsrichting
Woord   'spontaan' weglaten.

**Comment by MarijkeHuijgen** [comment]
Het woord 'spontaan' is weggehaald.
