### ISSUE TITLE
Formulering in Toelichting Wettelijk kader

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#43]
Mariëlle van Vliet, TNO: 

## Type issue
Publieke consultatie

## Waar
Toelichting   3 Wettelijk kader en monitoringdoel, 1e alinea

## Samenvatting
Niet eens met formulering van alinea.

## Beschrijving
> De   (her)gebruikswaarde van de gegevenssets die daarmee ontstaan, overtreft die van de afzonderlijke   onderzoeksgegevens:

'Overtreft' lijkt me niet een juist woord om hier te gebruiken. Ook   "andere" data is zeer goed herbruikbaar.

## Oplossingsrichting
ander   woordgebruik

**Comment by MarijkeHuijgen** [comment]
Bedoeld wordt dat het groeperen van de onderzoeksgegevens extra (her)gebruikswaarde toevoegt, bovenop de (her)gebruikswaarde van de 'losse' onderzoeksgegevens.

De tekst in de catalogus aangepast naar:
"Naast de (her)gebruikswaarde van de afzonderlijke onderzoeksgegevens, ontstaat hiermee toegevoegde (her)gebruikswaarde door groepering in een gegevensset. Bestuursorganen en andere gebruikers worden met deze gegevenssets in staat gesteld om huidige en toekomstige geohydrologische vraagstukken beter en efficiënter te beantwoorden."
