### ISSUE TITLE
Leesbaarheid toelichting meetpunten

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#44]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting   4 Meetpunten, allerlaatste alinea

## Samenvatting
De tekst is hier onduidelijk.

## Beschrijving

> Vervolgens   past de basisregistratie ondergrond elke keer wanneer een bronhouder een   verandering doorgeeft in de meetpunten van een monitoringnet als dat nodig is   ook de waarde van buis in gebruik aan voor de betreffende buizen in   grondwatermonitoringputten. Zodat buis in gebruik op 'ja' staat wanneer er   binnen één of  meerdere   grondwatermonitoringnetten op de huidige datum een meetpunt is dat naar de   betreffende buis in de put verwijst. En het op 'nee' staat wanneer dit niet   het geval is.

Tekst is slecht leesbaar. 

## Oplossingsrichting

Graag   leesbare tekst maken. Nu moet deze tekst meerdere keren worden gelezen,   voordat het te begrijpen is.

Bij "..., zodat ..." is een bijzin.   Daarvoor zou je een komma moeten plaatsen, maar dan wordt de zin te   lang.

**Comment by MarijkeHuijgen** [comment]
Alinea verduidelijkt in catalogus voor betere leesbaarheid.
