### ISSUE TITLE
Onduidelijkheid Toelichting Object met levensloop

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#45]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting   5 Object met levensloop, 3e alinea

## Samenvatting
Ook van meetpunten van beëindigde meetnetten wil je nog data kunnen opvragen. De tekst is hier onduidelijk over. 

## Beschrijving

> Per   die datum worden ook alle nog actieve meetpunten van het   grondwatermonitoringnet beëindigd.

Wat betekent dit voor het opvragen van gegevens uit een grondwatermeetnet   dat beeindigd is? Je wilt daarna ook nog steeds data van de bijbehorende   meetpunten op kunnen vragen. Wordt hierin voorzien?

Zie ook #19. 

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by MarijkeHuijgen** [comment]
De gegevens blijven gewoon beschikbaar, ook als het grondwatermonitoringnet en de bijbehorende meetpunten een einddatum hebben gekregen. De einddatum van een meetpunt geeft alleen maar aan dat na die datum het betreffende putfilter niet meer als meetpunt onderdeel is van het grondwatermonitoringnet. Als het grondwatermonitoringnet eindigt (een einddatum krijgt), dan krijgen ook alle meetpunten in het grondwatermonitoringnet diezelfde einddatum (als ze nog geen einddatum hebben).

In de catalogus de tekst aangepast om dit te verduidelijken:
"De basisregistratie ondergrond vult dan voor alle nog actieve meetpunten van het grondwatermonitoringnet dezelfde einddatum in. De gegevens van het grondwatermonitoringnet en de onderzoeken die eraan gekoppeld zijn blijven na die einddatum opvraagbaar voor gebruikers."
