### ISSUE TITLE
Schrijffout in Toelichting 7 Kwaliteitsregime IMBRO/A

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#46]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting,   7 Kwaliteitsregime IMBRO/A, 1e alinea

## Samenvatting
Schrijffout

## Beschrijving
> Een   belangrijk aandachtpunt in het…

Schrijffout.

## Oplossingsrichting
Aandachtpunt   moet zijn aandacht**s**punt

**Comment by MarijkeHuijgen** [comment]
Aangepast
