### ISSUE TITLE
Grondwateraspect onder IMBRO/A

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#47]
**Mariëlle van Vliet, TNO:** 

## Type issue
Publieke consultatie

## Waar
Toelichting,   7 Kwaliteitsregime IMBRO/A, 2e alinea

## Samenvatting
Grondwateraspect zou onder IMBRO/A ook altijd bekend moeten zijn.

## Beschrijving

> .. Wanneer het monitoringdoel onbekend is, kan de   bronhouder ervoor kiezen om het grondwateraspect 'onbekend' vast te leggen,   in plaats van specifiek 'kwaliteit' of 'kwantiteit'.

Het is mijn inziens altijd bekend welk grondwateraspect (kwaliteit of   kwantiteit) is gemonitord. Als dit niet duidelijk is dan lijkt me het opnemen   van een grondwatermeetnet niet nuttig.

## Oplossingsrichting
Als   dit niet duidelijk is dan lijkt me het opnemen van een grondwatermeetnet niet   nuttig.

**Comment by MarijkeHuijgen** [comment]
De optie 'onbekend' is alleen voor IMBRO/A. Het is een voorziening voor bronhouders om een overkoepelend grondwatermonitoringnet te registreren om hun historische GAR's en GLD's aan te koppelen als niet meer te achterhalen is voor welk grondwatermonitoringnet/monitoringdoel ze precies gemeten zijn.

In de catalogus de tekst aangepast om dit te verduidelijken:
"Voor historische onderzoeksgegevens zijn het wettelijk kader en het monitoringdoel niet altijd bekend. Deze historische gegevens kunnen aan een grondwatermontoringnet gekoppeld worden met kwaliteitsregime IMBRO/A. Onder kwaliteitsregime IMBRO/A is het mogelijk om grondwatermonitoringnetten te definiëren zonder specifiek wettelijk kader (kader aanlevering 'archiefoverdracht') en zonder specifiek monitoringdoel (monitoringdoel 'onbekend'). Wanneer het monitoringdoel 'onbekend' opgegeven is, kan de bronhouder er daarnaast voor kiezen om het grondwateraspect 'onbekend' vast te leggen, in plaats van specifiek 'kwaliteit' of 'kwantiteit'. Op deze manier heeft de bronhouder de mogelijkheid om één grondwatermonitoringnet te definiëren waaraan alle onderzoeksgegevens uit archiefoverdracht gekoppeld kunnen worden die niet onder een ander monitoringnet met een specifiek monitoringdoel vallen."
