### ISSUE TITLE
Nog lopende meetnetten

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#48]
**Mariëlle van Vliet, TNO:** 

## Type issue
Publieke consultatie

## Waar
Toelichting,   7 Kwaliteitsregime IMBRO/A, 3e alinea

## Samenvatting
Uitzoeken of er meetnetten zijn die in het verleden zijn gestart en nog actief zijn. Onder welk kwaliteitsregime kunnen deze vallen?

## Beschrijving
> Grondwatermonitoringnetten   onder IMBRO/A moeten altijd betrekking hebben op een periode in het verleden:   bij registratie geeft de bronhouder een einddatum in het verleden op, of   anders de waarde 'onbekend'.

Zijn er ook geen meetnetten die in het verleden zijn   gestart, die nu nog lopen en wellicht onder IMBRO/A moeten worden ingevoerd   aangezien ze niet voldoen aan kwaliteitsregime van IMBRO?

## Oplossingsrichting
Kan   dit worden nagegaan ?

**Comment by AnnitaVijverberg** [comment]
Als het grondmonitoringnet nu nog actief is, dan moet het voldoen aan kwaliteitsregime IMBRO. De gegevens die daarvoor nodig zijn, zoals monitoringdoel en ingangsdatum, moeten dan bekend/te achterhalen zijn. 
Zie ook de definitie van IMBRO in de enumeratielijst voor kwaliteitsregime: 
IMBRO = De strikte kwaliteitseis die geldt voor alle objecten die actief zijn op of na het moment dat het registreren van grondwatermonitoringnetten in de basisregistratie ondergrond is gestart. Een object is actief tussen de begindatum en de einddatum. 
Terwijl IMBRO/A = De minder strikte kwaliteitseis die gebruikt kan zijn voor objecten die actief waren tot aan het moment dat het registreren van grondwatermonitoringnetten in de basisregistratie ondergrond is gestart. Een object is actief tussen de begindatum en de einddatum.
