### ISSUE TITLE
Verwijzen naar tijdelijke buizen / meerdere buizen

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#49]
**Mariëlle van Vliet, TNO:** 

## Type issue
Publieke consultatie

## Waar
Toelichting,   8 Samenhang en consisitentie, 2e pagina, 1e alinea, 1e bullet

## Samenvatting
Verwijzen naar tijdelijke buizen / meerdere buizen in huidige opzet niet mogelijk.

## Beschrijving
> vanuit Grondwatermonitoringnet,   Grondwatersamenstellingsonderzoek en Grondwaterstandonderzoek naar een buis   in een grondwatermonitoringput (buisverwijzing);

In bodemkwaliteitsmeetnetten wordt naast bodem ook grondwater bemonsterd.   Deze monsters zijn afkomstig uit tijdelijke peilbuizen, waarbij een   mengmonster wordt gemaakt uit meerdere peilbuizen. Verwijzing naar tijdelijke   buizen en naar meerdere buizen is volgens deze opzet niet geregeld!

## Oplossingsrichting
Scope   is nu niet duidelijk afgebakend. Met huidige scope zouden   bodemkwaliteitsmeetnetten en bijbehorende data ook de bro in moeten. Dit   betekent dat de buisverwijzing moet worden uitgebreid.

**Comment by MarijkeHuijgen** [comment]
Bodemkwaliteitsmeetnetten zijn niet in scope voor het registratieobject Grondwatermonitoringnet. Dit is in de catalogus verduidelijkt, zie ook #41.
