### ISSUE TITLE
Definities registratieobject

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#5]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
Pag 4: registratieobject

## Beschrijving
BRO-ID > definitie: hier wordt specifiek alleen grondwatersamenstellingsonderzoek genoemd maar dit kan dus ook grondwaterstand zijn.
Object-ID bronhouder: dit gaat om de naam van het monitoringnet zoals intern bij de bronhouder bekend? Logisch zou zijn om toch gelijk te trekken met de BRO naam

## Oplossingsrichting
Bij object-id bronhouder misschien een voorbeeld geven wat dat zoal kan zijn?

**Comment by MarijkeHuijgen** [comment]
BRO-ID:
Definitie gecorrigeerd. Het betreft grondwatermonitoringnet.

object-ID bronhouder:
Zie ook #25.
Het object-ID bronhouder is in de registratie opgenomen om de communicatie tussen de registerbeheerder en de bronhouder of dataleverancier te vergemakkelijken. Het kan gebruikt  worden als identificerend gegeven voordat er door de BRO een BRO-ID aan is toegekend. Bijvoorbeeld als er iets misgaat in het proces rond registreren van een object. 
De bronhouder kan zelf bepalen wat voor id of code hij hiervoor gebruikt. Het gegeven wordt alleen uitgeleverd aan bronhouder en dataleverancier.
