### ISSUE TITLE
Onduidelijke tekst in Toelichting 8 samenhang en consistentie

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#50]
**Mariëlle van Vliet, TNO:**

## Type issue
Publieke consultatie

## Waar
Toelichting,   8 Samenhang en consisitentie, 2e pagina, 2e alinea, 2e bullet

## Samenvatting
De tekst is hier onduidelijk.

## Beschrijving
De   tekst bij deze bullet is me niet duidelijk.     Waar verwijst het "betreffende" filter naar?          In een filter kan een grondwatermonster worden genomen met een provinciaal   onderzoeksdoel (-meetnet), maar welke niet behoort tot het KRW-onderzoek (ofwel KRW-meetnet) (provincie   heeft bijv. hogere meetfrequentie).

## Oplossingsrichting
Graag   tekst verduidelijken!

**Comment by MarijkeHuijgen** [comment]
In de catalogus de tekst aangepast om dit te verduidelijken:
De verzameling meetpunten binnen een grondwatermonitoringnet is consistent met de grondwatersamenstellingsonderzoeken en grondwaterstandonderzoeken die in het kader van het monitoringnet zijn uitgevoerd. Dat wil zeggen: ten tijde van het uitvoeren van het onderzoek vormt het filter in de put waarin het onderzoek plaatsvindt, een meetpunt in elk grondwatermonitoringnet waaraan het betreffende onderzoek gekoppeld is.
