### ISSUE TITLE
Onjuiste verwijzing naar wettekst

### ISSUE THREAD

**Issue by lvdbrink** [BROprogramma/GMN#51]
**Mariëlle van Vliet, TNO:** 

## Type issue
Publieke consultatie

## Waar
Bijlage:   wettelijk kader en monitoringsdoel,   Kaderrichtlijn water

## Samenvatting
Onjuiste verwijzing naar wettekst.

## Beschrijving
> ...vastgelegd in Wet milieubeheer: art   1.2 (lid 1 en 2a)

Volgens mij is dit niet de juiste verwijzing.

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by MarijkeHuijgen** [comment]
De kaderrichtlijn water (Richtlijn 2000/60/EG) is Europees. De Wet milieubeheer bevat de vastlegging in de Nederlandse wet van de KRW-verplichtingen. 
Maar aangezien de verwijzing naar de Wet milieubeheer voor verwarring zorgt, is die verwijderd uit de catalogus.
