### ISSUE TITLE
Registreren hoe lang zijn meetpunten actief (zullen zijn)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/GMN#52]
## Type issue
Review sessie 

## Waar
5.3.3

## Samenvatting
Als data leverancier wil ik graag van meetpunten weten hoe lang ze nog actief zullen zijn zodat ik eventueel bestaande putten kan hergebruiken voor andere doelen.

## Beschrijving
Voort gekomen uit de sprintreview van 29 aug. Data leverenaciers willen zoveel als mogelijk hergebruik maken van putten die er al zijn en willen zo nauwkeurig mogelijke informatie op basis waarvan ingeschat kan worden of een bestaand meetpunt hergebruikswaarde heeft.

## Oplossingsrichting
Aangeven tot wanneer de eigenaar van een meetpunt garandeerd dat een put gebruikt wordt voor metingen.

**Comment by HanWelmer** [comment]
Opgenomen als Jira Issue in de BRO Funnel (Beheerfase). Zie https://jira.gdnnet.nl/browse/BROF-105
Daarmee is dit GMN BROProgramma issue afgesloten.
