### ISSUE TITLE
dezelfde buis kan meerdere malen aan een meetnet worden gekoppeld

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/GMN#61]
## Type issue
Testbevinding op GMN

## Waar
GMN Cat 5.3.6 GMW-monitoringbuis

## Samenvatting
Er is geen regel die voorkomt dat dezelfde buis meerdere malen aan een meetnet kan worden gekoppeld. Is dit de bedoeling?

## Oplossingsrichting
Tenzij er een reden is dit niet te doen: fomuleer een regel die voorkomt dat dezelfde buis meerdere malen aan een meetnet kan worden gekoppeld.

**Comment by HanWelmer** [comment]
De oplossingsrichting is niet correct. De combinatie van **broId** en **buisnummer** van een GMW buisverwijzing hoeft niet uniek te zijn binnen een GMN grondwatermonitoringnet.

In de [GMN Berichtencatalogus inname](https://www.bro-productomgeving.nl/bpo/latest/grondwatermonitoring/grondwatermonitoringnet-gmn/gmn-berichtencatalogus-innamewebservice/gmn-bci-levensloop#id-.GMNBCILevensloopvrelease1.4_Q3_2021-Aanvullenderegels) staat wel de volgende aanvullende regel:
De combinatie van **broId** (BRO-ID), **tubeNumber** (buisnummer) en **startDate** (startdatum buisverwijzing), als identificerend gegeven van een buisverwijzing, moet uniek zijn binnen een meetpunt van een grondwatermonitoringnet.
