### ISSUE TITLE
GMN: geen expliciete regel op bestaan van GMW put/buis

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/GMN#62]
## Type issue
ontbrekende regel/controle op put/buis verwijzing bij meetpunt

## Waar
GMN (berichten)catalogus

## Samenvatting
Er is geen regel/controle geformuleerd dat de put/buis waarnaar bij de meetpunten wordt verwezen ook werkelijk in de RO moet voorkomen. 

## Beschrijving
De aanname is dat een dergelijke controle wel moet plaatsvinden, dat zou in lijn zijn met een dergelijke regel voor b.v. KvK-nummer wel opgevoerd ("De organisatie moet binnen de basisregistratie ondergrond als bronhouder van grondwatermonitoringnet bekend zijn.").

## Oplossingsrichting
Het BRO LV team bouwt de controle in, in de aanname dat de put/buis wel moet bestaan in de RO

**Comment by AnnitaVijverberg** [comment]
In de toelichtende tekst van de catalogus staat:
"De basisregistratie ondergrond dwingt alleen af dat gegevens in andere registratieobjecten waarnaar verwezen wordt, ook daadwerkelijk geregistreerd zijn. Dit geldt voor de volgende verwijzingen (zie ook het plaatje in § 3.2 Domein grondwatermonitoring in de basisregistratie ondergrond):
- Vanuit Grondwatermonitoringnet, Grondwatersamenstellingsonderzoek en Grondwaterstandonderzoek naar een monitoringbuis in een grondwatermonitoringput."

Die zinsnede stuurt aan op een controle.
Waar wel rekening mee gehouden moet worden: Stel een put wordt kapot gereden en er wordt een put naast de eerst ingericht. Bij het meetpunt kan de aangepaste buisverwijzing pas worden geregistreerd (GMN_TubeReference) als de nieuwe put is geslagen en is geregistreerd in de BRO. In de tussentijd kan de bronhouder de oude put al hebben 'opgeruimd' in de BRO. Op dat moment verwijst een meetpunt in GMN dus naar een put en buis van een opgeruimte/voltooide put. Dat moet in de praktijk mogelijk zijn.

Kortom, er kan denk ik een controle plaatsvinden op het bestaan van de put en de buis in de BRO maar als een put wordt opgeruimd moet dit geen consequentie hebben voor de gekoppelde GMNen

**Comment by HanWelmer** [comment]
In de [GMN Berichtencatalogus inname](https://www.bro-productomgeving.nl/bpo/latest/grondwatermonitoring/grondwatermonitoringnet-gmn/gmn-berichtencatalogus-innamewebservice/gmn-bci-levensloop#id-.GMNBCILevensloopvrelease1.4_Q3_2021-Aanvullenderegels) staan de volgende aanvullende regels:

- De buisverwijzing moet wijzen naar een bestaande en bruikbare GMW monitoringbuis:

- In de BRO moet een GMW **GroundwaterMonitoringWell** (Grondwatermonitoringput) aanwezig zijn met een **broId** (BRO-ID) gelijk aan de **broId** (BRO-ID) van de **monitoringTube** (monitoringbuis).

- In de betreffende grondwatermonitoringput moet een **MonitoringTube** (Monitoringbuis) aanwezig zijn met een **tubeNumber** (buisnummer) gelijk aan het **tubeNumber** (buisnummer) van de **monitoringTube** (monitoringbuis).

- Op de **startDate** (begindatum buisverwijzing) moet het gegeven **tubeStatus** (buisstatus), van de monitoringbuis in de grondwatermonitoringput waarnaar de buisverwijzing verwijst, de waarde 'gebruiksklaar' hebben.
