### ISSUE TITLE
Afwezigheid regel die stelt dat combinatie buisnummer en bro_id uniek moet zijn binnen net

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/GMN#63]
## Type issue
Review

## Waar
p.5.3.5

## Samenvatting
Er wordt wel gesteld (als regel0 dat de `meetpuntcode` uniek is binnen een netwerk, echter niet de attributen van de `GMW-Monitoringbuis` Voor een correcte werking is dit wel nodig.

## Beschrijving
Het samenstel van attributen in een `Meetpunt` moet uniek zijn binnen een monitoring netwerk om te voorkomen dat netwerken zoals deze geconstrueerd worden:

```
Netwerk 1.
M1: code 1, broId = GMW000000101591, buis1
M2: code 2, broId = GMW000000101591, buis1
```

## Oplossingsrichting
Voeg de regels in de catalogus toe en maak de catalogus consistent op dit punt

**Comment by AnnitaVijverberg** [comment]
#61

**Comment by HanWelmer** [comment]
De oplossingsrichting is niet correct. De combinatie van **broId** en **buisnummer** van een GMW buisverwijzing hoeft niet uniek te zijn binnen een GMN grondwatermonitoringnet.

In de [GMN Berichtencatalogus inname](https://www.bro-productomgeving.nl/bpo/latest/grondwatermonitoring/grondwatermonitoringnet-gmn/gmn-berichtencatalogus-innamewebservice/gmn-bci-levensloop#id-.GMNBCILevensloopvrelease1.4_Q3_2021-Aanvullenderegels) staat wel de volgende aanvullende regel:
De combinatie van **broId** (BRO-ID), **tubeNumber** (buisnummer) en **startDate** (startdatum buisverwijzing), als identificerend gegeven van een buisverwijzing, moet uniek zijn binnen een meetpunt van een grondwatermonitoringnet.
