### ISSUE TITLE
Inconsistentie in isgmn-messages.xsd

### ISSUE THREAD

**Issue by PeterDorsman** [BROprogramma/GMN#66]
## Type issue
isgmn-messages.XSD  

## Waar
MeasuringPoint

## Samenvatting
binnen de XSD zijn verplichte elementen aanwezig waarbinnen het enigste hierbinnnen gelegen element weer optioneel is

## Beschrijving
Volgens de xsd is <**m**easuringPoint> een verplicht element
echter het enige hierbinnen gelegen element <**M**easuringPoint> is weer optioneel
Volgens de xsd is <**m**onitoringTube> een verplicht element
echter het enige hierbinnen gelegen element <**Groundwater**Monitoringtube> is weer optioneel

![Knipsel](https://user-images.githubusercontent.com/40062889/80602772-d29fb780-8a2f-11ea-94b3-84a99c0514a1.PNG)

## Oplossingsrichting
Maak de optionele elementen verplicht

**Comment by HanWelmer** [comment]
Binnen isgmn-messages.xsd zijn de PropertyType complexTypes aangepast, zodat alleen de by-value optie mogelijk is en niet de by-reference optie. Als gevolg daarvan zijn er geen optionele elementen op deze plekken.

Issue is daarmee opgelost.
