### ISSUE TITLE
Onmogelijk de geschiedenis van een netwerk zonder directe toegang (DB) tot de LV weer te geven.

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/GMN#68]
## Type issue
Maak visualisatie los van de BRO LV database mogelijk

## Waar
Uitgifte berichten catalogus

## Samenvatting
Het is niet mogelijk om te reconstrueren welke meetpunten zijn veranderd bij een aanvulling in de uitgifte.

## Beschrijving
Als PO van de LV wil ik graag de geschiedenis van een netwerk in een onafhankelijke service kunnen bouwen. Daartoe wil ik de meetpunten (ID) beschikbaar hebben bij de uitgifte op volledige geschiedenis. Dit is incluis start registratie (afwijking van GMW). 

## Oplossingsrichting
Voeg aan de gebeurtenissen in de uitgifte op geschiedenis de betreffende ID's toe zodat op basis van het uitgifte resultaat alleen, de geschiedenis kan worden weergegeven.

**Comment by HanWelmer** [comment]
Opgenomen in versie 1.2.0 van de GMN Berichtencatalogis uitgiftewebservice.
