### ISSUE TITLE
Inname berichten catalogus

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/GMN#69]
## Type issue
Controle op tijd is te streng

## Waar
berichten catalogus, diverse plekken

## Samenvatting
Aanleiding: "fouten gevonden door test". Echter deze fouten komen voor uit een bewuste keuze. Het betreft de categorie regels:
_De ...Date moet liggen voor de ..Date_ 

Er is vanuit functioneel oogpunt binnen de realisatie voor gekozen om deze regel te verruimen en een standaard volgorde op een datum te hanteren.

## Beschrijving

Binnen GMW is het mogelijk om verschillende gebeurtenissen op een datum te rapporteren. Dit willen we graag consistent houden met GMN. Echter, dan moet er wel een logische volgorde verondersteld zijn.

De volgorde is als volgt:

1. GMN_StartRegistration
2. GMN_MeasuringPoint
3. GMN_TubeReference
4. GMN_MeasuringPointEndDate
5.  GMN_Closure

Dit is vanuit gebruikersperspectief ook wenselijk: je hoeft niet een dag te wachten met het aanpassen van de buisverwijzing als je een nieuw meetpunt hebt toegevoegd. Zolang deze volgorde maar duidelijk is.

De tekst in de berichtencatalogus lijkt iets dergelijks ook te impliceren in hoofdstuk 2.1.3 Aanvullende regels: _"Een soortgelijke gebeurtenis (bepaalde waarde voor eventName (naam gebeurtenis)) mag niet meerdere keren voorkomen op dezelfde dag (combinatie van eventName (naam gebeurtenis) en eventDate (datum gebeurtenis) moet uniek zijn)."_

## Oplossingsrichting
Graag de berichtencatalogus aan passen aan de geïmplementeerde volgorde. Wellicht handig om het principe een keer uit te leggen en er vervolgens naar te verwijzen. 

Wellicht op dezelfde plek als de volgorde van onvolledige datums worden uitgelegd (kan dit even niet vinden): van onvolledig naar volledig. Dus:

**'1999'** komt chronologisch voor **'jan-1999'** komt chronologisch voor **'1-jan-1999'**

**Comment by HanWelmer** [comment]
Verwerkt in versie 1.2.2 (17-12-2021) van de GMN Berichtencatalogus uitgifte.
