### ISSUE TITLE
Definities relaties

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#7]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
Pag 8: overzicht relaties >Rol naam met kardinaliteiten.

## Beschrijving
Hier wordt alleen grondwatersamenstellingsonderzoek beschreven maar dat kan ook grondwaterstandonderzoek zijn, waarom wordt het niet genoemd?

**Comment by MarijkeHuijgen** [comment]
Het gaat om grondwatermonitoringnet (i.p.v. grondwatersamenstellingsonderzoek). Aangepast in catalogus.
