### ISSUE TITLE
Definitie dataleverancier

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#8]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
1.1.1.4 dataleverancier

## Beschrijving
Moet dit niet kvk nummer zijn?

**Comment by MarijkeHuijgen** [comment]
Het formaat van het attribuut 'dataleverancier' is Organisatie. Organisatie is een keuze tussen kvk-nummer en Europees handelsnummer.
