### ISSUE TITLE
Koppeling met GMW

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GMN#9]
Janco van Gelderen, Provincie Utrecht:
## Type issue
Publieke consultatie

## Waar
Pag 17: objectype meetpunt en Pag 18: 1.1.3.4.1 + 1.1.3.4.2. BRO-ID + buisverwijzing

## Beschrijving
BRO-ID > hier is het relevant te weten welke link gelegd wordt. Met het onherkenbare kale BRO ID of met de herkenbare ‘putcode’. Dat laatste is wenselijk dus GWM23A0003214.001. Het is nu niet helder hoe dat gebeurt.  Vraag is nu hoe filter hierin meegenomen wordt. Qua koppeling. 

## Oplossingsrichting
Maak de koppeling met de betekenisvolle putcode, niet met het BRO-ID.

**Comment by PRNienhuis-WN** [comment]
Zie ook bij GAR issue #60.
Vraag is of alles wat in de catalogi staat ook voor "eindgebruikers" letterlijk zo zichtbaar is of dat die catalogi alleen dienen voor de formele beschrijving (dus meer a la "datamodel").

Bij verwijzingen naar een GMW, zoals die in GLD, GAR en GMN komen te staan, lijken me de kale BRO-IDs juist essentieel omdat alleen zo'n kaal BRO-ID gegarandeerd uniek is.
Ik kan me voorstellen dat bij de software die je gebruikt voor aanlevering aan het bronhouderportaal in de presentatielaag in ieder geval wel de herkenbare "putcode" en filteraanduiding staat. Dat die software dat achter de schermen vertaalt naar zo'n kaal BRO-ID lijkt me dan logisch.
Dito voor uitlevering aan BRO-gebruikers.

**Comment by AnnitaVijverberg** [comment]
**provincies via Platform Meetnetbeheerders:**
Er heeft reeds veel overleg plaats gevonden rondom een betekenisvol ID van grondwatermonitoringputten in de BRO. Dit heeft geleid tot de Putcode, waarin de NITG code is verwerkt. Een erg belangrijke afspraak (waar mogelijk nog niet iedereen van op de hoogte is). De Putcode is echter niet in de catalogus benoemd. De gemaakte afspraken rondom Putcode graag borgen in de catalogus(sen). De omschrijving zoals verwoord in de catalogus Grondwatermonitoringput is inmiddels achterhaald.

Ook: Toelichting   op pagina 28/35
In de toelichting staat: Om aan te geven op welke locaties er onderzoek wordt gedaan ten behoeve van het monitoringdoel, ligt bij een grondwatermonitoringnet vast welke meetpunten onderdeel zijn van het net. Een meetpunt wordt gevormd door een filter dat zich in een buis van een grondwatermonitoringput bevindt. In de basisregistratie ondergrond ligt bij een meetpunt de verwijzing naar deze buis vast, door middel van het BRO-ID van de grondwatermonitoringput en het buisnummer. Ik neem aan dat de verwijzing ook via Putcode kan plaats vinden en niet alleen per BRO-ID? Graag duidelijkheid verschaffen.

**Comment by lvdbrink** [comment]
**Mariëlle van Vliet, TNO:** 

Is er   nog een andere verwijzing dan BRO-ID, buisnummer mogelijk?

De   grondwaterkwaliteitsmeetnetten maken gebruik van een uniek RIVM-nr per put en   een toevoeging van een cijfer (1, 2 etc) voor de filters.     Nummers <1000 zijn LMG, nummers 1800-2000 prov NB, nrs 2200-2400 zijn   van Limburg etc.          Kan dit ergens worden opgeslagen? Bij put is daar mijn inziens geen   rekening mee gehouden. Aan alle PMG en LMG-putten is dit nummer toegekend.

**Comment by MarijkeHuijgen** [comment]
Er is een werkafspraak i.v.m. de putcode in voorbereiding voor het registratieobject Grondwatermonitoringput.

Het BRO-ID wordt door de hele BRO gebruikt als het identificerende gegeven van een registratieobject. Het informatiemodel geeft aan hoe de gegevens formeel zijn geordend. Daarom maken we in het informatiemodel gebruik van het BRO-ID.
Het unieke BRO-ID van de grondwatermonitoringput geeft ook toegang tot de putcode (en andere gegevens van de put). Er zijn manieren waarbij de bronhouder in zijn eigen software gebruik kan maken van de putcode (en het BRO-ID) waarbij de aanlevering, aanvulling en correctie wel via het formele BRO-ID verloopt.
De wens om als gebruiker putcode te gebruiken i.p.v. BRO-ID is een functionele vraag, die niet in de catalogus wordt geadresseerd omdat de catalogus niet bedoeld is voor het beschrijven van dit soort functionaliteit. 

In het registratieobject Grondwatermonitoringput is inderdaad geen RIVM-nummer opgenomen. Aangezien het gaat om een gegeven dat hoort bij een put, is het registratieobject Grondwatermonitoringput de plek om dit op te nemen als dat nodig is, en niet het registratieobject Grondwatermonitoringnet. Als in de praktijk blijkt dat er grote behoefte is aan het vastleggen van de RIVM-nummering, dan kan dit als wens ingediend worden bij het registratieobject Grondwatermonitoringput.
